###회원가입
POST localhost:8080/mirror/member/signup
Content-Type: application/json

{
  "loginId":"barbo9510",
  "password":"test1234!",
  "name":"테스트",
  "email": "test1234@test.test",
  "area": "INCH"
}

###로그인
POST localhost:8080/mirror/member/login
Content-Type: application/json

{
  "loginId":"barbo9510",
  "password":"test1234!"
}
> {%
  client.global.set("Token",response.body.data.accessToken);
  %}

###정보 조회
GET localhost:8080/mirror/member/info
Authorization: Bearer {{Token}}

###거울 등록
POST localhost:8080/mirror/member/mirror/add
Content-Type: application/json
Authorization: Bearer {{Token}}

{
  "mirrorCode": "100001c3322242920e",
  "mirrorName" : "테스트의 거울"
}

###거울 삭제
DELETE localhost:8080/mirror/member/mirror/{mirrorId}
Authorization: Bearer {{Token}}


### 거울 리스트
GET localhost:8080/mirror/member/mirror
Authorization: Bearer {{Token}}
