### 현재날씨 검색
GET localhost:8080/mirror/weather/shortTerm/인천광역시서구
### 현재날씨 회원
GET localhost:8080/mirror/weather/shortTerm
Authorization: Bearer {{Token}}
### 현재날씨 거울
GET localhost:8080/mirror/weather/mirror/shortTerm
mirrorCode: 100001c3322242920e
### 대피소 검색
GET localhost:8080/mirror/weather/shelter/인천서구심곡동
### 대피소 회원
GET localhost:8080/mirror/weather/shelter
Authorization: Bearer {{Token}}
### 재난 문자
GET localhost:8080/mirror/weather/disasterMsg
Authorization: Bearer {{Token}}
### 지도 날씨 출력 회원
GET localhost:8080/mirror/weather/weatherMapService
Authorization: Bearer {{Token}}
### 지도 날씨 거울
GET localhost:8080/mirror/weather/weatherMapService/mirror
mirrorCode: 100001c3322242920e
###
GET localhost:8080/mirror/weather/typhoon

###

GET localhost:8080/mirror/weather/aws

###

GET localhost:8080/mirror/weather/live

###
GET localhost:8080/mirror/weather/weatherMapService
