### 현재날씨 검색
GET localhost:8080/mirror/weather/shortTerm/인천광역시서구
### 현재날씨 회원
GET localhost:8080/mirror/weather/shortTerm
Authorization: Bearer {{Token}}
### 현재날씨 거울
GET localhost:8080/mirror/weather/mirror/shortTerm
mirrorCode: 100001c3322242920e
### 대피소 검색
GET localhost:8080/mirror/weather/shelter/인천서구심곡동
### 대피소 회원
GET localhost:8080/mirror/weather/shelter
Authorization: Bearer {{Token}}
### 재난 문자
GET localhost:8080/mirror/weather/disasterMsg
Authorization: Bearer {{Token}}
### 지도 날씨 출력 회원
GET localhost:8080/mirror/weather/weatherMapService
Authorization: Bearer {{Token}}
### 지도 날씨 거울
GET localhost:8080/mirror/weather/weatherMapService/mirror
mirrorCode: 100001c3322242920e
### 미세 먼지
GET localhost:8080/mirror/weather/dust
### 미세 먼지 회원
GET localhost:8080/mirror/weather/dust/member
Authorization: Bearer {{Token}}
### 미세 먼지 거울
GET localhost:8080/mirror/weather/dust/mirror
### 전국 미세 먼지 예보
GET localhost:8080/mirror/weather/nation/dust
### 일주일 날씨 회원
GET localhost:8080/mirror/weather/weekWeather/member
Authorization: Bearer {{Token}}
### 일주일 날씨 거울
GET localhost:8080/mirror/weather/weekWeather/mirror
mirrorCode: 100001c3322242920e
### 거울 단기 조회
GET localhost:8080/mirror/weather/mirror/shortTerm/point
mirrorCode: 100001c3322242920e
### 특보
GET localhost:8080/mirror/weather/specialReport
###
GET localhost:8080/mirror/weather/typhoon

###

GET localhost:8080/mirror/weather/aws

###

GET localhost:8080/mirror/weather/live

###
GET localhost:8080/mirror/weather/weatherMapService
